<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mozi [
    <!ELEMENT mozi (film)*>

        <!ELEMENT film (rendezo+,szinesz+,iro+)>
        <!ATTLIST film id ID #REQUIRED>
        <!ATTLIST film mufaj (horror | romantikus | theiller) "horror">

        <!ELEMENT rendezo EMPTY>
        <!ATTLIST rendezo id ID #REQUIRED>
        <!ATTLIST rendezo nev CDATA #IMPLIED>

        <!ELEMENT szinesz EMPTY>
        <!ATTLIST szinesz id ID #REQUIRED>
        <!ATTLIST szinesz nev CDATA #IMPLIED>

        <!ELEMENT iro EMPTY>
        <!ATTLIST iro id ID #REQUIRED>
]>

<mozi>
    
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex"/>
        <szinesz id="u5g_4xm_2jb" nev="Madison_Ivy"/>
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkronszinesz />
        </szinesz>
        <iro id="trv_4xm_2jb" />
    </film>

    <film id="txn_nxm_3jb" mufaj="drama">
        <rendezo id="nzk_4xm_3jb">
            <rendezo1 nev="alexa" />
            <rendezo2 nev="valaki" />
        </rendezo>
        <szinesz id="u5g_4xm_3jb" nev="Madison_Ivy"/>
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkronszinesz />
        </szinesz>
        <iro id="trv_4xm_3jb">
            <iro1 />
            <iro2 />
        </iro>
    </film>

</mozi>